# Generated by Django 4.2.10 on 2025-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LATE", "Retard"),
                            ("EARLY_DEPARTURE", "Départ anticipé"),
                            ("MISSING_ARRIVAL", "Arrivée manquante"),
                            ("MISSING_DEPARTURE", "Départ manquant"),
                            ("INSUFFICIENT_HOURS", "Heures insuffisantes"),
                            (
                                "CONSECUTIVE_SAME_TYPE",
                                "Pointages consécutifs du même type",
                            ),
                            ("ANOMALY_REPORTED", "Anomalie signalée"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=30,
                        verbose_name="type d'alerte",
                    ),
                ),
                ("message", models.TextField(verbose_name="message")),
                (
                    "recipients",
                    models.TextField(
                        help_text="Séparez les emails par des virgules",
                        verbose_name="destinataires",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("SENT", "Envoyé"),
                            ("FAILED", "Échec"),
                            ("RESOLVED", "Résolu"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="statut",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyé le"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="message d'erreur"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "alerte",
                "verbose_name_plural": "alertes",
                "ordering": ["-created_at"],
            },
        ),
    ]
