# Generated by Django 4.2.10 on 2025-03-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesheets", "0001_initial"),
        ("alerts", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="anomaly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="timesheets.anomaly",
                verbose_name="anomalie",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employé",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="sites.site",
                verbose_name="site",
            ),
        ),
    ]
