# Generated by Django 4.2.10 on 2025-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="recipients",
            field=models.TextField(
                help_text="Séparez les emails par des virgules. Inclut automatiquement le manager du site.",
                verbose_name="destinataires",
            ),
        ),
    ]
