# Generated by Django 4.2.10 on 2025-03-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Journalier"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("MONTHLY", "Mensuel"),
                            ("CUSTOM", "Personnalisé"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="type de rapport",
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("PDF", "PDF"), ("EXCEL", "Excel")],
                        default="PDF",
                        max_length=20,
                        verbose_name="format de rapport",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="date de début")),
                ("end_date", models.DateField(verbose_name="date de fin")),
                (
                    "file",
                    models.FileField(upload_to="reports/", verbose_name="fichier"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="créé par",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="organizations.organization",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "rapport",
                "verbose_name_plural": "rapports",
                "ordering": ["-created_at"],
            },
        ),
    ]
