# Generated by Django 4.2.10 on 2025-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Journalier"),
                            ("WEEKLY", "Hebdomadaire"),
                            ("MONTHLY", "Mensuel"),
                            ("CUSTOM", "Personnalisé"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                        verbose_name="type de rapport",
                    ),
                ),
                (
                    "report_format",
                    models.CharField(
                        choices=[("CSV", "CSV"), ("PDF", "PDF"), ("EXCEL", "Excel")],
                        default="PDF",
                        max_length=20,
                        verbose_name="format de rapport",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="date de début")),
                ("end_date", models.DateField(verbose_name="date de fin")),
                (
                    "file",
                    models.FileField(upload_to="reports/", verbose_name="fichier"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
            ],
            options={
                "verbose_name": "rapport",
                "verbose_name_plural": "rapports",
                "ordering": ["-created_at"],
            },
        ),
    ]
