# Generated by Django 4.2.10 on 2025-03-26 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0007_remove_schedule_allow_early_arrival_and_more"),
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="name",
        ),
        migrations.AlterField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="créé par",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="reports/", verbose_name="fichier"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_format",
            field=models.CharField(
                choices=[("PDF", "PDF"), ("EXCEL", "Excel")],
                default="PDF",
                max_length=10,
                verbose_name="format du rapport",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("TIMESHEET", "Pointages"),
                    ("ANOMALY", "Anomalies"),
                    ("EMPLOYEE", "Employés"),
                ],
                max_length=20,
                verbose_name="type de rapport",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="sites.site",
                verbose_name="site",
            ),
        ),
    ]
