# Generated by Django 4.2.10 on 2025-04-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_org_id'),
        ('reports', '0004_report_name_alter_report_report_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization', verbose_name='organisation'),
        ),
    ]
