# Generated by Django 5.1.5 on 2025-01-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistiquestemps',
            name='minutes_manquantes_total',
        ),
        migrations.RemoveField(
            model_name='statistiquestemps',
            name='nb_absences_totales',
        ),
        migrations.RemoveField(
            model_name='statistiquestemps',
            name='nb_presences_partielles',
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='minutes_absence',
            field=models.IntegerField(default=0, help_text="Total des minutes d'absence sur le mois"),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='minutes_depart_anticipe',
            field=models.IntegerField(default=0, help_text='Total des minutes de départ anticipé sur le mois'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='minutes_retard',
            field=models.IntegerField(default=0, help_text='Total des minutes de retard sur le mois'),
        ),
    ]
