# Generated by Django 5.1.5 on 2025-01-24 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_remove_statistiquestemps_minutes_manquantes_total_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='statistiquestemps',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='planning',
            name='duree_prevue_minutes',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='marge_duree_pct',
        ),
        migrations.AddField(
            model_name='anomalie',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='planning',
            name='duree_min',
            field=models.IntegerField(default=216, verbose_name='Durée prévue (en minutes)'),
        ),
        migrations.AddField(
            model_name='planning',
            name='frequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fréquence (en jours)'),
        ),
        migrations.AddField(
            model_name='planning',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='site',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_temps', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='type_anomalie',
            field=models.CharField(choices=[('retard', 'Retard'), ('depart_anticipe', 'Départ anticipé'), ('absence', 'Absence'), ('presence_partielle', 'Présence partielle'), ('incoherence', 'Incohérence')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='qr_code_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('name', 'organisation'), ('qr_code_value', 'organisation')},
        ),
        migrations.AlterUniqueTogether(
            name='statistiquestemps',
            unique_together={('user', 'site', 'organisation', 'mois', 'annee')},
        ),
    ]
