# Generated by Django 5.1.5 on 2025-01-24 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_statistiquestemps_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointage',
            options={'ordering': ['date_scan']},
        ),
        migrations.RemoveField(
            model_name='planning',
            name='marge_pop_up',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='users',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='arrivee_ou_depart',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='periode',
        ),
        migrations.AddField(
            model_name='planning',
            name='marge_duree_pct',
            field=models.IntegerField(default=10, verbose_name='Marge de tolérance sur la durée (%)'),
        ),
        migrations.AddField(
            model_name='planning',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='ecart_duree_minutes',
            field=models.IntegerField(default=0, help_text='Écart par rapport à la durée prévue (pour planning FREQUENCE)'),
        ),
    ]
