# Generated by Django 5.1.5 on 2025-01-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pointage_options_remove_planning_marge_pop_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planning',
            name='jours_passage',
        ),
        migrations.AddField(
            model_name='planning',
            name='dimanche',
            field=models.BooleanField(default=False, verbose_name='Dimanche'),
        ),
        migrations.AddField(
            model_name='planning',
            name='jeudi',
            field=models.BooleanField(default=False, verbose_name='Jeudi'),
        ),
        migrations.AddField(
            model_name='planning',
            name='lundi',
            field=models.BooleanField(default=False, verbose_name='Lundi'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mardi',
            field=models.BooleanField(default=False, verbose_name='Mardi'),
        ),
        migrations.AddField(
            model_name='planning',
            name='mercredi',
            field=models.BooleanField(default=False, verbose_name='Mercredi'),
        ),
        migrations.AddField(
            model_name='planning',
            name='samedi',
            field=models.BooleanField(default=False, verbose_name='Samedi'),
        ),
        migrations.AddField(
            model_name='planning',
            name='vendredi',
            field=models.BooleanField(default=False, verbose_name='Vendredi'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='duree_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée prévue (en minutes)'),
        ),
    ]
