# Generated by Django 5.1.5 on 2025-02-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250205_1454'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE core_site ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
            ALTER TABLE core_site ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
            
            ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
            ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
            
            ALTER TABLE core_pointage ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
            ALTER TABLE core_pointage ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
            """,
            reverse_sql="""
            ALTER TABLE core_site DROP COLUMN IF EXISTS created_at;
            ALTER TABLE core_site DROP COLUMN IF EXISTS updated_at;
            
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS created_at;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS updated_at;
            
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS created_at;
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS updated_at;
            """
        ),
    ] 