# Generated by Django 5.1.5 on 2025-02-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_timestamps'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                BEGIN
                    ALTER TABLE core_site ADD COLUMN created_at timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                BEGIN
                    ALTER TABLE core_site ADD COLUMN updated_at timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                BEGIN
                    ALTER TABLE core_statistiquestemps ADD COLUMN created_at timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                BEGIN
                    ALTER TABLE core_statistiquestemps ADD COLUMN updated_at timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                BEGIN
                    ALTER TABLE core_pointage ADD COLUMN created_at timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                BEGIN
                    ALTER TABLE core_pointage ADD COLUMN updated_at timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_site DROP COLUMN IF EXISTS created_at;
            ALTER TABLE core_site DROP COLUMN IF EXISTS updated_at;
            
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS created_at;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS updated_at;
            
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS created_at;
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS updated_at;
            """
        ),
    ]
