# Generated by Django 5.1.5 on 2025-02-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_timestamps'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                BEGIN
                    ALTER TABLE core_site ADD COLUMN adresse text;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_site DROP COLUMN IF EXISTS adresse;
            """
        ),
    ] 