# Generated by Django 5.1.5 on 2025-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_site_address'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                BEGIN
                    ALTER TABLE core_pointage ADD COLUMN periode varchar(20);
                    ALTER TABLE core_pointage ADD COLUMN type_pointage varchar(10);
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS periode;
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS type_pointage;
            """
        ),
    ] 