# Generated by Django 5.1.5 on 2025-02-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_pointage_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                -- Anomalie
                BEGIN
                    ALTER TABLE core_anomalie ADD COLUMN IF NOT EXISTS date_creation timestamp with time zone DEFAULT now();
                    ALTER TABLE core_anomalie ADD COLUMN IF NOT EXISTS type_anomalie varchar(20) DEFAULT 'autre';
                    ALTER TABLE core_anomalie ADD COLUMN IF NOT EXISTS motif text;
                    ALTER TABLE core_anomalie ADD COLUMN IF NOT EXISTS status varchar(20) DEFAULT 'en_attente';
                    ALTER TABLE core_anomalie ADD COLUMN IF NOT EXISTS commentaire_traitement text;
                    ALTER TABLE core_anomalie ADD COLUMN IF NOT EXISTS date_traitement timestamp with time zone;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;

                -- StatistiquesTemps
                BEGIN
                    ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS mois integer;
                    ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS annee integer;
                    ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS minutes_retard integer DEFAULT 0;
                    ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS minutes_depart_anticipe integer DEFAULT 0;
                    ALTER TABLE core_statistiquestemps ADD COLUMN IF NOT EXISTS minutes_absence integer DEFAULT 0;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            -- Anomalie
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS date_creation;
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS type_anomalie;
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS motif;
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS status;
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS commentaire_traitement;
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS date_traitement;

            -- StatistiquesTemps
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS mois;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS annee;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS minutes_retard;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS minutes_depart_anticipe;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS minutes_absence;
            """
        ),
    ] 