# Generated by Django 5.1.5 on 2025-03-14 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0011_add_missing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomalie',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Anomalie', 'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterModelOptions(
            name='planning',
            options={'ordering': ['-actif', 'site__name'], 'verbose_name': 'Planning', 'verbose_name_plural': 'Plannings'},
        ),
        migrations.AlterModelOptions(
            name='pointage',
            options={'ordering': ['-date_scan'], 'verbose_name': 'Pointage', 'verbose_name_plural': 'Pointages'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['name'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='statistiquestemps',
            options={'ordering': ['-annee', '-mois'], 'verbose_name': 'Statistiques de temps', 'verbose_name_plural': 'Statistiques de temps'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterUniqueTogether(
            name='statistiquestemps',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='anomalie',
            name='date_declaration',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='ecart_duree_minutes',
        ),
        migrations.AddField(
            model_name='anomalie',
            name='commentaire_traitement',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire de traitement'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='date_traitement',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/', verbose_name='Justificatif'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='minutes_manquantes',
            field=models.IntegerField(default=0, help_text='Nombre de minutes manquantes (retard, départ anticipé, absence)', verbose_name='Minutes manquantes'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AddField(
            model_name='anomalie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='planning',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='planning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='commentaire',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='periode',
            field=models.CharField(choices=[('MATIN', 'Matin'), ('APRES_MIDI', 'Après-midi'), ('HORS_PLAGE', 'Hors plage')], default='HORS_PLAGE', max_length=20, verbose_name='Période'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='type_pointage',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], default='ENTREE', max_length=10, verbose_name='Type de pointage'),
        ),
        migrations.AddField(
            model_name='pointage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='site',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse du site'),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='date_derniere_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='jours_travailles',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Jours travaillés'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='minutes_travaillees',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutes travaillées'),
        ),
        migrations.AddField(
            model_name='statistiquestemps',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='motif',
            field=models.TextField(verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('justifiee', 'Justifiée'), ('non_justifiee', 'Non justifiée'), ('en_cours', 'En cours de traitement')], default='en_attente', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='type_anomalie',
            field=models.CharField(choices=[('retard', 'Retard'), ('depart_anticipe', 'Départ anticipé'), ('absence', 'Absence'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name="Type d'anomalie"),
        ),
        migrations.AlterField(
            model_name='anomalie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='planning',
            name='type',
            field=models.CharField(choices=[('FIXE', 'Fixe'), ('FREQUENCE', 'Fréquence')], max_length=10, verbose_name='Type de planning'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date_scan',
            field=models.DateTimeField(verbose_name='Date et heure du scan'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='depart_anticip',
            field=models.IntegerField(default=0, help_text='Nombre de minutes de départ anticipé', verbose_name='Départ anticipé (minutes)'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='core.planning', verbose_name='Planning associé'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='retard',
            field=models.IntegerField(default=0, help_text='Nombre de minutes de retard', verbose_name='Retard (minutes)'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='core.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='site',
            name='emails_alertes',
            field=models.TextField(blank=True, help_text="Liste d'emails séparés par des virgules pour les notifications", null=True, verbose_name='Emails pour les alertes'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='site',
            name='qr_code_value',
            field=models.CharField(max_length=100, verbose_name='Valeur du QR Code'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='annee',
            field=models.PositiveSmallIntegerField(verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='minutes_absence',
            field=models.PositiveIntegerField(default=0, verbose_name="Minutes d'absence"),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='minutes_depart_anticipe',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutes de départ anticipé'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='minutes_retard',
            field=models.PositiveIntegerField(default=0, verbose_name='Minutes de retard'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='mois',
            field=models.PositiveSmallIntegerField(verbose_name='Mois'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='core.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='statistiquestemps',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='auth.group', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('gardien', 'Gardien'), ('agent_de_nettoyage', 'Agent de nettoyage'), ('manager', 'Manager')], default='gardien', help_text="Rôle de l'utilisateur dans l'application", max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de dernière modification'),
        ),
        migrations.AlterUniqueTogether(
            name='statistiquestemps',
            unique_together={('user', 'site', 'mois', 'annee')},
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['user', 'date_creation'], name='core_anomal_user_id_a9db23_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['site', 'date_creation'], name='core_anomal_site_id_3bd683_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['type_anomalie'], name='core_anomal_type_an_8ca7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalie',
            index=models.Index(fields=['status'], name='core_anomal_status_43b0d3_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['user', 'date_scan'], name='core_pointa_user_id_99f2f7_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['site', 'date_scan'], name='core_pointa_site_id_f4db6d_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['date_scan'], name='core_pointa_date_sc_7d4fb1_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['periode'], name='core_pointa_periode_913b57_idx'),
        ),
        migrations.AddIndex(
            model_name='pointage',
            index=models.Index(fields=['type_pointage'], name='core_pointa_type_po_cb4831_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiquestemps',
            index=models.Index(fields=['user', 'annee', 'mois'], name='core_statis_user_id_fea4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='statistiquestemps',
            index=models.Index(fields=['site', 'annee', 'mois'], name='core_statis_site_id_f3edb6_idx'),
        ),
    ]
