# Generated by Django 5.1.5 on 2025-03-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_anomalie_options_alter_planning_options_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                BEGIN
                    ALTER TABLE core_pointage ADD COLUMN commentaire text NULL;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_pointage DROP COLUMN IF EXISTS commentaire;
            """
        ),
    ]
