# Generated by Django 5.1.5 on 2025-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_commentaire_to_pointage'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                BEGIN
                    ALTER TABLE core_statistiquestemps ADD COLUMN minutes_travaillees integer DEFAULT 0;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS minutes_travaillees;
            """
        ),
    ] 