# Generated by Django 5.1.5 on 2025-03-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_minutes_travaillees_to_statistiquestemps'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                -- Ajouter justificatif à Anomalie
                BEGIN
                    ALTER TABLE core_anomalie ADD COLUMN justificatif varchar(100) NULL;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                -- Ajouter jours_travailles à StatistiquesTemps
                BEGIN
                    ALTER TABLE core_statistiquestemps ADD COLUMN jours_travailles smallint DEFAULT 0;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS justificatif;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS jours_travailles;
            """
        ),
    ] 