# Generated by Django 5.1.5 on 2025-03-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_missing_columns'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                -- Ajouter traite_par_id à Anomalie
                BEGIN
                    ALTER TABLE core_anomalie ADD COLUMN traite_par_id integer NULL;
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
                
                -- Ajouter date_derniere_maj à StatistiquesTemps
                BEGIN
                    ALTER TABLE core_statistiquestemps ADD COLUMN date_derniere_maj timestamp with time zone DEFAULT now();
                EXCEPTION
                    WHEN duplicate_column THEN NULL;
                END;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE core_anomalie DROP COLUMN IF EXISTS traite_par_id;
            ALTER TABLE core_statistiquestemps DROP COLUMN IF EXISTS date_derniere_maj;
            """
        ),
    ] 