# Generated by Django 4.2.10 on 2025-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "org_id",
                    models.CharField(
                        help_text="ID unique de l'organisation sur 3 chiffres",
                        max_length=3,
                        unique=True,
                        verbose_name="ID Organisation",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="adresse")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="code postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "country",
                    models.CharField(
                        default="France", max_length=100, verbose_name="pays"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email de contact"
                    ),
                ),
                (
                    "siret",
                    models.CharField(blank=True, max_length=14, verbose_name="SIRET"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="organizations/logos/",
                        verbose_name="logo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
                "ordering": ["name"],
            },
        ),
    ]
