# Generated by Django 4.2.10 on 2025-03-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="ville"),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email de contact"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(
                default="France", max_length=100, verbose_name="pays"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="notes",
            field=models.TextField(blank=True, verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="organization",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=5, verbose_name="code postal"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="siret",
            field=models.CharField(blank=True, max_length=14, verbose_name="SIRET"),
        ),
    ]
