# Generated by Django 4.2.10 on 2025-03-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_city_organization_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="org_id",
            field=models.CharField(
                default=0,
                help_text="ID unique de l'organisation sur 3 chiffres",
                max_length=3,
                unique=True,
                verbose_name="ID Organisation",
            ),
            preserve_default=False,
        ),
    ]
