# Generated by Django 4.2.10 on 2025-03-26 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("timesheets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_timesheets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="corrigé par",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employé",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheets",
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AddField(
            model_name="employeereport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employé",
            ),
        ),
        migrations.AddField(
            model_name="employeereport",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_reports",
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_anomalies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="corrigé par",
            ),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employé",
            ),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anomalies",
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AddField(
            model_name="anomaly",
            name="timesheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anomalies",
                to="timesheets.timesheet",
                verbose_name="pointage",
            ),
        ),
    ]
