# Generated by Django 4.2.10 on 2025-03-24 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="corrected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="corrected_timesheets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="corrigé par",
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="correction_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date de correction"
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="correction_note",
            field=models.TextField(blank=True, verbose_name="note de correction"),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="geolocation_enabled",
            field=models.BooleanField(
                default=True, verbose_name="géolocalisation activée"
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="is_ambiguous",
            field=models.BooleanField(default=False, verbose_name="pointage ambigu"),
        ),
    ]
