# Generated by Django 4.2.10 on 2025-03-26 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("timesheets", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeereport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "rapport d'employé",
                "verbose_name_plural": "rapports d'employés",
            },
        ),
        migrations.AlterField(
            model_name="employeereport",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employé",
            ),
        ),
        migrations.AlterField(
            model_name="employeereport",
            name="total_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="total des heures",
            ),
        ),
    ]
