# Generated by Django 4.2.10 on 2025-03-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "timesheets",
            "0002_timesheet_corrected_by_timesheet_correction_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheet",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=13,
                null=True,
                verbose_name="latitude",
            ),
        ),
        migrations.AlterField(
            model_name="timesheet",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                max_digits=13,
                null=True,
                verbose_name="longitude",
            ),
        ),
    ]
