# Generated by Django 4.2.10 on 2025-04-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0003_alter_employeereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='scan_type',
            field=models.CharField(choices=[('NFC', 'NFC'), ('QR_CODE', 'QR Code')], default='NFC', max_length=10, verbose_name='type de scan'),
        ),
    ]
