# Generated by Django 4.2.10 on 2025-04-10 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_remove_siteemployee_unique_site_employee_schedule_and_more'),
        ('timesheets', '0005_alter_timesheet_latitude_alter_timesheet_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='related_timesheets',
            field=models.ManyToManyField(blank=True, related_name='related_anomalies', to='timesheets.timesheet', verbose_name='pointages associés'),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='sites.schedule', verbose_name='planning'),
        ),
    ]
