# Generated by Django 4.2.10 on 2025-04-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0006_anomaly_related_timesheets_anomaly_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='anomaly_type',
            field=models.CharField(choices=[('LATE', 'Retard'), ('EARLY_DEPARTURE', 'Départ anticipé'), ('MISSING_ARRIVAL', 'Arrivée manquante'), ('MISSING_DEPARTURE', 'Départ manquant'), ('INSUFFICIENT_HOURS', 'Heures insuffisantes'), ('CONSECUTIVE_SAME_TYPE', 'Pointages consécutifs du même type'), ('UNLINKED_SCHEDULE', 'Planning non lié'), ('OTHER', 'Autre')], max_length=30, verbose_name="type d'anomalie"),
        ),
    ]
