# Generated by Django 4.2.10 on 2025-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixe (gardien)"),
                            ("FREQUENCY", "Fréquence (nettoyage)"),
                        ],
                        default="FIXED",
                        max_length=20,
                        verbose_name="type de planning",
                    ),
                ),
                (
                    "min_daily_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="heures minimales par jour",
                    ),
                ),
                (
                    "min_weekly_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="heures minimales par semaine",
                    ),
                ),
                (
                    "allow_early_arrival",
                    models.BooleanField(
                        default=True, verbose_name="autoriser arrivée en avance"
                    ),
                ),
                (
                    "allow_late_departure",
                    models.BooleanField(
                        default=True, verbose_name="autoriser départ tardif"
                    ),
                ),
                (
                    "early_arrival_limit",
                    models.PositiveIntegerField(
                        default=30, verbose_name="limite arrivée en avance (minutes)"
                    ),
                ),
                (
                    "late_departure_limit",
                    models.PositiveIntegerField(
                        default=30, verbose_name="limite départ tardif (minutes)"
                    ),
                ),
                (
                    "break_duration",
                    models.PositiveIntegerField(
                        default=60, verbose_name="durée de pause (minutes)"
                    ),
                ),
                (
                    "min_break_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="début pause au plus tôt"
                    ),
                ),
                (
                    "max_break_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="fin pause au plus tard"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "planning",
                "verbose_name_plural": "plannings",
                "ordering": ["site", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="jour de la semaine",
                    ),
                ),
                ("start_time_1", models.TimeField(verbose_name="heure de début 1")),
                ("end_time_1", models.TimeField(verbose_name="heure de fin 1")),
                (
                    "start_time_2",
                    models.TimeField(
                        blank=True, null=True, verbose_name="heure de début 2"
                    ),
                ),
                (
                    "end_time_2",
                    models.TimeField(
                        blank=True, null=True, verbose_name="heure de fin 2"
                    ),
                ),
            ],
            options={
                "verbose_name": "détail du planning",
                "verbose_name_plural": "détails des plannings",
                "ordering": ["schedule", "day_of_week"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("address", models.TextField(verbose_name="adresse")),
                (
                    "postal_code",
                    models.CharField(max_length=5, verbose_name="code postal"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="ville")),
                (
                    "country",
                    models.CharField(
                        default="France", max_length=100, verbose_name="pays"
                    ),
                ),
                (
                    "nfc_id",
                    models.CharField(
                        help_text="Format: S0001 à S9999",
                        max_length=5,
                        unique=True,
                        verbose_name="ID Site",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sites/qrcodes/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "late_margin",
                    models.PositiveIntegerField(
                        default=15, verbose_name="marge de retard (minutes)"
                    ),
                ),
                (
                    "early_departure_margin",
                    models.PositiveIntegerField(
                        default=15, verbose_name="marge de départ anticipé (minutes)"
                    ),
                ),
                (
                    "ambiguous_margin",
                    models.PositiveIntegerField(
                        default=20, verbose_name="marge pour cas ambigus (minutes)"
                    ),
                ),
                (
                    "alert_emails",
                    models.TextField(
                        blank=True,
                        help_text="Séparez les emails par des virgules",
                        verbose_name="emails pour alertes",
                    ),
                ),
                (
                    "require_geolocation",
                    models.BooleanField(
                        default=True, verbose_name="géolocalisation requise"
                    ),
                ),
                (
                    "geolocation_radius",
                    models.PositiveIntegerField(
                        default=100, verbose_name="rayon de géolocalisation (mètres)"
                    ),
                ),
                (
                    "allow_offline_mode",
                    models.BooleanField(
                        default=True, verbose_name="autoriser le mode hors ligne"
                    ),
                ),
                (
                    "max_offline_duration",
                    models.PositiveIntegerField(
                        default=24, verbose_name="durée maximale hors ligne (heures)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SiteEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
            ],
            options={
                "verbose_name": "employé du site",
                "verbose_name_plural": "employés du site",
            },
        ),
    ]
