# Generated by Django 4.2.10 on 2025-03-24 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                ("address", models.TextField(verbose_name="adresse")),
                (
                    "nfc_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID NFC"
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="sites/qrcodes/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "late_margin",
                    models.PositiveIntegerField(
                        default=15, verbose_name="marge de retard (minutes)"
                    ),
                ),
                (
                    "early_departure_margin",
                    models.PositiveIntegerField(
                        default=15, verbose_name="marge de départ anticipé (minutes)"
                    ),
                ),
                (
                    "alert_emails",
                    models.TextField(
                        blank=True,
                        help_text="Séparez les emails par des virgules",
                        verbose_name="emails pour alertes",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="organizations.organization",
                        verbose_name="organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "site",
                "verbose_name_plural": "sites",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixe (gardien)"),
                            ("FREQUENCY", "Fréquence (nettoyage)"),
                        ],
                        default="FIXED",
                        max_length=20,
                        verbose_name="type de planning",
                    ),
                ),
                (
                    "min_daily_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="heures minimales par jour",
                    ),
                ),
                (
                    "min_weekly_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="heures minimales par semaine",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="mis à jour le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="sites.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "planning",
                "verbose_name_plural": "plannings",
                "ordering": ["site", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="créé le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="actif")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_sites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="employé",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_employees",
                        to="sites.schedule",
                        verbose_name="planning",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="sites.site",
                        verbose_name="site",
                    ),
                ),
            ],
            options={
                "verbose_name": "employé du site",
                "verbose_name_plural": "employés du site",
                "unique_together": {("site", "employee")},
            },
        ),
        migrations.CreateModel(
            name="ScheduleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        verbose_name="jour de la semaine",
                    ),
                ),
                ("start_time_1", models.TimeField(verbose_name="heure de début 1")),
                ("end_time_1", models.TimeField(verbose_name="heure de fin 1")),
                (
                    "start_time_2",
                    models.TimeField(
                        blank=True, null=True, verbose_name="heure de début 2"
                    ),
                ),
                (
                    "end_time_2",
                    models.TimeField(
                        blank=True, null=True, verbose_name="heure de fin 2"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="sites.schedule",
                        verbose_name="planning",
                    ),
                ),
            ],
            options={
                "verbose_name": "détail du planning",
                "verbose_name_plural": "détails des plannings",
                "ordering": ["schedule", "day_of_week"],
                "unique_together": {("schedule", "day_of_week")},
            },
        ),
    ]
