# Generated by Django 4.2.10 on 2025-03-26 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteemployee",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_sites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="employé",
            ),
        ),
        migrations.AddField(
            model_name="siteemployee",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_employees",
                to="sites.schedule",
                verbose_name="planning",
            ),
        ),
        migrations.AddField(
            model_name="siteemployee",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="organizations.organization",
                verbose_name="organisation",
            ),
        ),
        migrations.AddField(
            model_name="scheduledetail",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="sites.schedule",
                verbose_name="planning",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="sites.site",
                verbose_name="site",
            ),
        ),
        migrations.AddConstraint(
            model_name="siteemployee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("site", "employee", "schedule"),
                name="unique_active_site_employee_schedule",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduledetail",
            unique_together={("schedule", "day_of_week")},
        ),
    ]
