# Generated by Django 4.2.10 on 2025-03-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="allow_early_arrival",
            field=models.BooleanField(
                default=True, verbose_name="autoriser arrivée en avance"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="allow_late_departure",
            field=models.BooleanField(
                default=True, verbose_name="autoriser départ tardif"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="break_duration",
            field=models.PositiveIntegerField(
                default=60, verbose_name="durée de pause (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="early_arrival_limit",
            field=models.PositiveIntegerField(
                default=30, verbose_name="limite arrivée en avance (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="late_departure_limit",
            field=models.PositiveIntegerField(
                default=30, verbose_name="limite départ tardif (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="max_break_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="fin pause au plus tard"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="min_break_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="début pause au plus tôt"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="allow_offline_mode",
            field=models.BooleanField(
                default=True, verbose_name="autoriser le mode hors ligne"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="ambiguous_margin",
            field=models.PositiveIntegerField(
                default=20, verbose_name="marge pour cas ambigus (minutes)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="geolocation_radius",
            field=models.PositiveIntegerField(
                default=100, verbose_name="rayon de géolocalisation (mètres)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="max_offline_duration",
            field=models.PositiveIntegerField(
                default=24, verbose_name="durée maximale hors ligne (heures)"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="require_geolocation",
            field=models.BooleanField(
                default=True, verbose_name="géolocalisation requise"
            ),
        ),
    ]
