# Generated by Django 4.2.10 on 2025-03-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0003_alter_siteemployee_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="siteemployee",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="siteemployee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("site", "employee", "schedule"),
                name="unique_active_site_employee_schedule",
            ),
        ),
    ]
