# Generated by Django 4.2.10 on 2025-03-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_siteemployee_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="city",
            field=models.CharField(
                default="Ville", max_length=100, verbose_name="ville"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="site",
            name="country",
            field=models.CharField(
                default="France", max_length=100, verbose_name="pays"
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="postal_code",
            field=models.CharField(
                default="94230", max_length=5, verbose_name="code postal"
            ),
            preserve_default=False,
        ),
    ]
