# Generated by Django 4.2.10 on 2025-03-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_site_nfc_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="nfc_id",
            field=models.CharField(
                help_text="Format: FFF-Sxxxx où FFF est l'ID de l'organisation et xxxx est un nombre entre 0001 et 9999",
                max_length=10,
                unique=True,
                verbose_name="ID Site",
            ),
        ),
    ]
