# Generated by Django 4.2.10 on 2025-03-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0005_alter_site_nfc_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["site"],
                "verbose_name": "planning",
                "verbose_name_plural": "plannings",
            },
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="name",
        ),
    ]
