# Generated by Django 4.2.10 on 2025-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0006_alter_schedule_options_remove_schedule_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="allow_early_arrival",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="allow_late_departure",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="break_duration",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="early_arrival_limit",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="late_departure_limit",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="max_break_end",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="min_break_start",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="min_daily_hours",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="min_weekly_hours",
        ),
        migrations.AddField(
            model_name="scheduledetail",
            name="day_type",
            field=models.CharField(
                choices=[
                    ("FULL", "Journée entière"),
                    ("AM", "Matin"),
                    ("PM", "Après-midi"),
                ],
                default="FULL",
                max_length=4,
                verbose_name="type de journée",
            ),
        ),
        migrations.AddField(
            model_name="scheduledetail",
            name="frequency_duration",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Pour les plannings de type fréquence uniquement",
                null=True,
                verbose_name="durée en minutes",
            ),
        ),
        migrations.AddField(
            model_name="site",
            name="frequency_tolerance",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Pourcentage de tolérance pour la durée des plannings fréquence",
                verbose_name="tolérance planning fréquence (%)",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledetail",
            name="end_time_1",
            field=models.TimeField(
                blank=True, null=True, verbose_name="heure de fin 1"
            ),
        ),
        migrations.AlterField(
            model_name="scheduledetail",
            name="start_time_1",
            field=models.TimeField(
                blank=True, null=True, verbose_name="heure de début 1"
            ),
        ),
    ]
