# Generated by Django 4.2.10 on 2025-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0007_remove_schedule_allow_early_arrival_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="alert_emails",
            field=models.TextField(
                blank=True,
                help_text="Séparez les emails par des virgules. Les alertes seront également envoyées au manager du site.",
                verbose_name="emails pour alertes",
            ),
        ),
    ]
