# Generated by Django 4.2.10 on 2025-03-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_site_alert_emails'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siteemployee',
            name='unique_active_site_employee_schedule',
        ),
        migrations.AddIndex(
            model_name='siteemployee',
            index=models.Index(fields=['schedule', 'is_active'], name='sites_sitee_schedul_769894_idx'),
        ),
        migrations.AddIndex(
            model_name='siteemployee',
            index=models.Index(fields=['site', 'is_active'], name='sites_sitee_site_id_f89d20_idx'),
        ),
        migrations.AddConstraint(
            model_name='siteemployee',
            constraint=models.UniqueConstraint(fields=('site', 'employee'), name='unique_site_employee'),
        ),
    ]
