# Generated by Django 4.2.10 on 2025-04-01 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_org_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0009_remove_siteemployee_unique_active_site_employee_schedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='manager',
        ),
        migrations.AddField(
            model_name='schedule',
            name='employees',
            field=models.ManyToManyField(help_text='Employés assignés à ce planning', related_name='schedules', through='sites.SiteEmployee', to=settings.AUTH_USER_MODEL, verbose_name='employés'),
        ),
        migrations.AddField(
            model_name='site',
            name='employees',
            field=models.ManyToManyField(help_text='Employés assignés à ce site', related_name='sites', through='sites.SiteEmployee', to=settings.AUTH_USER_MODEL, verbose_name='employés'),
        ),
        migrations.AlterField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(help_text='Organisation à laquelle le site est rattaché', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organizations.organization', verbose_name='organisation'),
        ),
        migrations.AlterField(
            model_name='siteemployee',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'role': 'EMPLOYEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_sites', to=settings.AUTH_USER_MODEL, verbose_name='employé'),
        ),
        migrations.AlterField(
            model_name='siteemployee',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_employees', to='sites.schedule', verbose_name='planning'),
        ),
        migrations.AlterField(
            model_name='siteemployee',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_employees', to='sites.site', verbose_name='site'),
        ),
    ]
