# Generated by Django 4.2.10 on 2025-04-03 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_site_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='early_departure_margin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Marge de tolérance pour les départs anticipés (plannings fixes)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marge de départ anticipé (minutes)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='frequency_tolerance_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pourcentage de tolérance pour la durée de présence (plannings fréquence)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='marge de tolérance (%)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='late_arrival_margin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Marge de tolérance pour les retards (plannings fixes)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marge de retard (minutes)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='tolerance_margin',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Marge de tolérance générale (plannings fixes)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='marge de tolérance (minutes)'),
        ),
    ]
