# Generated by Django 4.2.10 on 2025-04-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_schedule_early_departure_margin_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siteemployee',
            name='unique_site_employee',
        ),
        migrations.AddConstraint(
            model_name='siteemployee',
            constraint=models.UniqueConstraint(fields=('site', 'employee', 'schedule'), name='unique_site_employee_schedule'),
        ),
    ]
