# Generated by Django 4.2.10 on 2025-04-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_remove_siteemployee_unique_site_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='tolerance_margin',
        ),
    ]
