# Generated by Django 4.2.10 on 2025-04-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0015_remove_siteemployee_unique_site_employee_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('FIXED', 'Fixe'), ('FREQUENCY', 'Fréquence')], default='FIXED', max_length=20, verbose_name='type de planning'),
        ),
    ]
