# Generated by Django 4.2.10 on 2025-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_alter_schedule_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='activation_end_date',
            field=models.DateField(blank=True, help_text='Date à partir de laquelle le site sera inactif', null=True, verbose_name="date de fin d'activation"),
        ),
        migrations.AddField(
            model_name='site',
            name='activation_start_date',
            field=models.DateField(blank=True, help_text='Date à partir de laquelle le site sera actif', null=True, verbose_name="date de début d'activation"),
        ),
    ]
