# Generated by Django 4.2.10 on 2025-03-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="scan_preference",
            field=models.CharField(
                choices=[
                    ("BOTH", "NFC et QR Code"),
                    ("NFC_ONLY", "NFC uniquement"),
                    ("QR_ONLY", "QR Code uniquement"),
                ],
                default="BOTH",
                max_length=20,
                verbose_name="préférence de scan",
            ),
        ),
    ]
