# Generated by Django 4.2.10 on 2025-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_org_id'),
        ('users', '0002_remove_user_organization_user_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organizations',
            field=models.ManyToManyField(help_text="Organisations auxquelles l'utilisateur est rattaché", related_name='users', to='organizations.organization', verbose_name='organisations'),
        ),
    ]
