# Generated by Django 4.2.10 on 2025-04-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text="ID unique de l'utilisateur au format UXXXXX", max_length=6, verbose_name='ID employé'),
        ),
    ]
