# Generated by Django 4.2.10 on 2025-03-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_scan_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="simplified_mobile_view",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, affiche uniquement le bouton de pointage sur mobile",
            ),
        ),
    ]
