# Generated by Django 4.2.10 on 2025-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', help_text="Langue préférée de l'utilisateur", max_length=2, verbose_name='langue'),
        ),
    ]
