# Generated by Django 4.2.10 on 2025-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_end_date',
            field=models.DateField(blank=True, help_text="Date à partir de laquelle l'utilisateur sera inactif", null=True, verbose_name="date de fin d'activation"),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_start_date',
            field=models.DateField(blank=True, help_text="Date à partir de laquelle l'utilisateur sera actif", null=True, verbose_name="date de début d'activation"),
        ),
    ]
